# Nombre del an치lisis
name: SonarCloud Analysis

# Configuraci칩n del an치lisis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    # Se ejecuta en una m치quina Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Paso para clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: 16.x

      # Paso para configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Paso para instalar dependencias
      - name: Clean npm cache
        run: npm cache clean --force
        
      # borrar Pjson  
      - name: Remove package-lock.json
        run: rm package-lock.json
      
      - name: Install dependencies
        run: npm install

      # Paso para ejecutar SonarCloud scanner
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
